"""add interview session fields

Revision ID: ef003375a27b
Revises: d60d51b58c94
Create Date: 2026-08-03 21:07:31.944054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef003375a27b'
down_revision: Union[str, Sequence[str], None] = 'd60d51b58c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "interview_sessions",
        sa.Column(
            "company",
            sa.String(length=100),
            nullable=True,
        ),
    )

    op.add_column(
        "interview_sessions",
        sa.Column(
            "interview_type",
            sa.String(length=50),
            nullable=True,
        ),
    )

    op.add_column(
        "interview_sessions",
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'completed_at')
    op.drop_column('interview_sessions', 'interview_type')
    op.drop_column('interview_sessions', 'company')
    # ### end Alembic commands ###
